- shell:
    - command: test -d ~/.asdf || git clone https://github.com/asdf-vm/asdf.git ~/.asdf
      description: Cloning asdf
    - command: git -C ~/.asdf checkout "$(git -C ~/.asdf describe --abbrev=0 --tags)"
      description: Selecting the latest asdf version
    - command: ~/.asdf/bin/asdf update
      description: Updating asdf
