- link:
    ~/.gitconfig: tools/git/gitconfig
    ~/.gitattributes: tools/git/gitattributes

- asdf:
  - plugin: git
    global: latest
    versions:
      - latest
- asdf:
  - plugin: pre-commit
    global: latest
    versions:
      - latest

