- asdf:
  - plugin: kubectl
    global: latest
    versions:
      - latest
  - plugin: helm
    global: latest
    versions:
      - latest
  - plugin: kustomize
    global: latest
    versions:
      - latest
