- asdf:
    - plugin: nodejs

- link:
    ~/.default-npm-packages: tools/npm/default-npm-packages

- asdf:
    - plugin: nodejs
      global: lts
      versions:
        - lts

    - plugin: yarn
      global: latest
      versions:
        - latest
