- asdf:
  - plugin: nodejs

- link:
    ~/.default-npm-packages: tools/npm/default-npm-packages

- shell:
    - [$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring]

- asdf:
  - plugin: nodejs
    global: latest
    versions:
      - latest

  - plugin: yarn
    global: latest
    versions:
      - latest
