- asdf:
  - plugin: nodejs

- shell:
    - [$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring]

- asdf:
  - plugin: nodejs
    versions:
      - latest

  - plugin: yarn
    versions:
      - latest
