- link:
    # ssh
    ~/.ssh/config: tools/ssh/config
    ~/.config/systemd/user/ssh-agent.service: tools/ssh/ssh-agent.service

- shell:
    - [systemctl --user enable ssh-agent.service, Enabling ssh-agent.service]
    - [systemctl --user start  ssh-agent.service, Starting ssh-agent.service]
