- asdf:
  - plugin: tflint
    global: latest
    versions:
      - latest
  - plugin: terraform-docs
    global: latest
    versions:
      - latest
- shell:
    - ["test -d ~/.tfenv || git clone https://github.com/tfutils/tfenv.git ~/.tfenv", "Cloning tfenv"]
    - ["git -C ~/.tfenv pull", "Selecting the latest tfenv version"]
- link:
    ~/.tfenv/use-gpgv: tools/tfenv/conf/use-gpgv
    ~/.tfenv/version: tools/tfenv/conf/version
