- asdf:
    - plugin: tmux
      global: latest
      versions:
        - latest

- link:
    ~/.tmux.conf: terminals/tmux/tmux.conf
    ~/.tmux/plugins/tpm: terminals/tmux/tpm
    ~/.tmux/scripts: terminals/tmux/scripts
