- shell:
    - [~/.dotfiles/scripts/install-zplug.sh, Installing zplug]

- link:
    # zsh
    ~/.zshrc: shells/zsh/zshrc
    ~/.zprofile: shells/zsh/zprofile
    ~/.exports.zsh: shells/zsh/exports.zsh
    ~/.aliases.zsh: shells/zsh/aliases.zsh
    ~/.p10k.zsh: shells/zsh/p10k.zsh
    ~/.profile: shells/zsh/profile
