- link:
    # zsh
    ~/.zshrc: shells/zsh/zshrc
    ~/.exports.zsh: shells/zsh/exports.zsh
    ~/.aliases.zsh: shells/zsh/aliases.zsh
    ~/.p10k.zsh: shells/zsh/p10k.zsh
    ~/.profile: shells/zsh/profile
