[Editor]
FontFamily = "RobotoMono Nerd Font"
FontSize = 14
Linespace = 6

ExtCmdline   = true
ExtPopupmenu = true
ExtTabline   = true
ExtMessages  = true

Clipboard = false

StartMaximizedWindow = false

IndentGuide = true

DrawBorderForFloatWindow = true

DrawShadowForFloatWindow = true

DesktopNotifications = true

ClickEffect = true

[MiniMap]
Disable = true

RestoreSession = true
