#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV="$BASE_DIR/install.env"

[[ -f $ENV ]] || (echo "$ENV: not found" && exit 1)

# shellcheck source=/dev/null
. "$ENV"

updateSubmodules

for config in "${@}"; do
  applyConfig "$config"
done
