#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV="$BASE_DIR/install.env"

[[ -f $ENV ]] || (echo "$ENV: not found" && exit 1)

# shellcheck source=/dev/null
. "$ENV"

PROFILE="$META_DIR/$PROFILES_DIR/$1"

[[ -f "$PROFILE" ]] || (echo "$PROFILE: not found" && exit 1)

updateSubmodules

echo -e "\nApplying profile $(basename "$PROFILE")..."

while IFS= read -r config; do
    CONFIGS+=" $config"
done < "$PROFILE"

shift

for config in $CONFIGS "${@}"; do
  applyConfig "$config"
done
