#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV="$BASE_DIR/install.env"

[[ -f $ENV ]] || (echo "$ENV: not found" && exit 1)

# shellcheck source=/dev/null
. "$ENV"

pushd "$BASE_DIR" > /dev/null

git -C "$BASE_DIR" submodule update --init --recursive --remote

for config in "${@}"; do
    PROFILE_CONFIG_PATH=$BASE_DIR/$META_DIR/$CONFIG_DIR/$config$CONFIG_SUFFIX

    configContent="$(<"$BASE_CONFIG_PATH")\n$(<"$PROFILE_CONFIG_PATH")"

    $DOTBOT_CMD \
      -d "$BASE_DIR" \
      --plugin-dir "$DOTBOT_PLUGINS/dotbot-asdf" \
      -c <(echo -e "$configContent")
done
