[theme]
theme = "semi-native"

[icons]
icons = "awesome"

[[block]]
block      = "disk_space"
alert_unit = "GB"
warning    = 50.0
alert      = 20.0

[[block]]
block       = "memory"
format_mem  = "$mem_avail.eng(3,B,M)($mem_avail_percents.eng(2))"
format_swap = "$swap_free.eng(3,B,M)($swap_free_percents.eng(2))"

[[block]]
block    = "cpu"
interval = 1
format = "$barchart.str() $utilization.eng()"
format_alt = "$frequency.eng() \\|$boost.str()"

[[block]]
block    = "load"
format   = "$1m"

[[block]]
block       = "battery"
format = "$percentage|N/A"

[[block]]
block = "pomodoro"
notify_cmd = "i3-nagbar -m '{msg}' -t warning"
blocking_cmd = true

[[block]]
block    = "time"
interval = 10
[block.format]
full   = "%a %d/%m %R"
short = "%R"
