export fpath=($HOME/.local/share/zsh/site-functions $fpath)

####  zplug setup
[ -f ~/.zplug/init.zsh ] && source ~/.zplug/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# perform tasks asynchronously
zplug "mafredri/zsh-async", defer:0

# syntax highlight in the terminal
zplug "zsh-users/zsh-syntax-highlighting", defer:3

# package manager for go, java, etc.
zplug "kiurchv/asdf.plugin.zsh", defer:2

# flexible clipboard use from CLI
zplug "zpm-zsh/clipboard"

# fish like auto suggestions
zplug "zsh-users/zsh-autosuggestions"

# interactive CLI git
zplug "wfxr/forgit", defer:1

# autostart tmux
#zplug "zpm-zsh/tmux"

# auto closes delimiters
zplug 'hlissner/zsh-autopair', defer:2

# vi mode plug-in
zplug "plugins/vi-mode", from:oh-my-zsh

# some oh-my-zsh useful plug-ins
zplug "lib/completion", from:oh-my-zsh
zplug "lib/grep", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "lib/directories", from:oh-my-zsh
zplug "lib/prompt_info_functions", from:oh-my-zsh

# zsh theme
zplug "themes/ys", from:oh-my-zsh

if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo
    zplug install
  fi
fi

zplug load
####  end zplug setup

which aws_completer >/dev/null 2>&1 && complete -C aws_completer aws

#
# Custom configurations
#

# brew autocomplete
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

setopt rmstarsilent

# mac keybindings
if [[ "$OSTYPE" == "darwin"* ]]; then
  bindkey "^[^[[D" backward-word
  bindkey "^[^[[C" forward-word

  bindkey "^[a" beginning-of-line
  bindkey "^[e" end-of-line

  bindkey "ç" fzf-cd-widget
fi

#
# Exports
#
[ -f ~/.exports.zsh ] && . ~/.exports.zsh

#
# Local exports
#
[ -f ~/.exports.local ] && . ~/.exports.local

# Aliases
[ -f ~/.aliases.zsh ] && source ~/.aliases.zsh

# Local configurations
[ -f ~/.zshrc_local ] && source ~/.zshrc_local

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# autosuggestions config
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)

# forgit config
FORGIT_FZF_DEFAULT_OPTS="
  --exact
  --border
  --cycle
  --reverse
  --height '80%'
"
# vi-mode config
VI_MODE_SET_CURSOR=true
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true

gpg-connect-agent updatestartuptty /bye >/dev/null

[ -f ~/.nix-profile/etc/profile.d/nix.sh ] && source ~/.nix-profile/etc/profile.d/nix.sh

## bindkeys

if which tmux_sessions >/dev/null 2>&1; then
  function new_tmux_session() {
    tmux_sessions
  }

  zle -N new_tmux_session{,}
  bindkey  new_tmux_session
fi

[[ $commands[terraform] ]] && complete -o nospace -C $commands[terraform] terraform

[[ $commands[kubectl] ]] && source <(kubectl completion zsh)

command -v direnv > /dev/null && eval "$(direnv hook zsh)"

command -v direnv > /dev/null && direnv() { asdf exec direnv "$@"; }

autoload -U +X bashcompinit && bashcompinit

complete -o nospace -C /home/sebas/.tfenv/versions/1.1.6/terraform terraform
