set nocompatible
filetype plugin on
syntax on

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" install plugins
call plug#begin('~/.vim/plugged')
  source ~/.vim/plugins.vim
call plug#end()

set splitbelow
set splitright
set relativenumber
set ignorecase
set smartcase
set incsearch
set showmatch

nnoremap th  :tabfirst<CR>
nnoremap tj  :tabnext<CR>
nnoremap tk  :tabprev<CR>
nnoremap tl  :tablast<CR>
nnoremap tt  :tabedit<Space>
nnoremap tn  :tabnext<Space>
nnoremap tm  :tabm<Space>
nnoremap td  :tabclose<CR>
nnoremap <leader><space>  :noh<CR>
nnoremap <leader>ev       <C-w><C-v><C-l>:e $MYVIMRC<cr>
nnoremap <leader>w        <C-w>v<C-w>l
nnoremap <C-h>            <C-w>h
nnoremap <C-j>            <C-w>j
nnoremap <C-k>            <C-w>k
nnoremap <C-l>            <C-w>l

inoremap jj <ESC>

set spelllang=es,en

set textwidth=110
set colorcolumn=+1
set hlsearch

autocmd BufRead,BufNewFile *.md setlocal spell
set complete+=kspell

au FileType vimwiki set syntax=pandoc
au FocusLost * :wa

" ### pandoc ###
let g:pandoc#spell#default_langs = ['en', 'es']
let g:pandoc#filetypes#handled = ['pandoc', 'markdown', 'textile', 'rst']
let g:pandoc#syntax#conceal#urls = 1
let g:pandoc#syntax#codeblocks#embeds#langs = ['python','java','scala','sh', 'c', 'sql']

" ### base16 ###
if filereadable(expand('~/.vimrc_background'))
  let base16colorspace=256
  source ~/.vimrc_background
endif

" ### airline ###
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts 		 = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme			 = 'base16'

" ### NERDTree ###
map <C-n> :NERDTreeToggle<CR>

" gnupg
let g:GPGDefaultRecipients = ['sebas@zaffarano.com.ar']

" ### Vimwiki config ###
" 1. define wikis
let wiki        = {}
let wiki.path   = '~/.wiki/'
let wiki.syntax = 'markdown'
let wiki.ext    = '.md'
" 2. 2. add wikis
let g:vimwiki_list          = [wiki]
let g:vimwiki_conceallevel  = 0

" ### ALE ###
let g:ale_completion_enabled = 1

" ### spellcheck highlights ###
highlight clear SpellBad
highlight clear SpellCap
highlight SpellBad cterm=underline ctermfg=red
highlight SpellCap cterm=underline ctermfg=green

" ### Lint ###
let g:ale_vim_vint_executable = expand('~/.local/anaconda3/bin/vint')
let g:ale_vim_vint_use_global = 1

" ### scalastyle ###
let g:ale_scalastyle_config_loc = expand('~/.scalastyle-config.xml')
