set nocompatible
filetype plugin on
syntax on

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'chriskempson/base16-vim'
Plug 'vimwiki/vimwiki', { 'branch': 'dev' }
Plug 'junegunn/seoul256.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'tbabej/taskwiki'
Plug 'powerman/vim-plugin-AnsiEsc'
Plug 'majutsushi/tagbar'
Plug 'blindFS/vim-taskwarrior'
Plug 'Shougo/unite.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'cespare/vim-toml'
Plug 'scrooloose/nerdcommenter'

call plug#end()

set t_Co&
set background=dark
let base16colorspace = 256

colorscheme base16-default-dark

set noshowcmd
set noshowmode

set number

set expandtab
set shiftround
set shiftwidth=2
set tabstop=2

set textwidth=110
set colorcolumn=+1

set splitbelow
set splitright

set relativenumber
set ignorecase
set smartcase
set incsearch
set showmatch

nnoremap <leader><space>  :noh<CR>
nnoremap <leader>ev       <C-w><C-v><C-l>:e $MYVIMRC<cr>
nnoremap <leader>w        <C-w>v<C-w>l
nnoremap <C-h>            <C-w>h
nnoremap <C-j>            <C-w>j
nnoremap <C-k>            <C-w>k
nnoremap <C-l>            <C-w>l

inoremap jj <ESC>

" vimwiki config
let g:vimwiki_list = [{ 'path': '~/.wiki/', 'syntax': 'markdown', 'ext': '.md'}]

autocmd BufRead,BufNewFile *.md setlocal spell
set complete+=kspell

au FileType vimwiki set syntax=pandoc
au FocusLost * :wa

let g:pandoc#spell#default_langs = ['en', 'es']
let g:pandoc#filetypes#handled = ["pandoc", "markdown", "textile", "rst"]
let g:pandoc#syntax#conceal#urls = 1
let g:pandoc#syntax#codeblocks#embeds#langs = ["python","java","scala","sh", "c", "sql"]

let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme='base16'
