set nocompatible
filetype off

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'chriskempson/base16-vim'

call plug#end()

set t_Co&
set background=dark
let base16colorspace = 256

colorscheme base16-default-dark

set noshowcmd
set noshowmode

set number

set expandtab
set shiftround
set shiftwidth=2
set tabstop=2

"set list listchars=tab:»·,trail:·,nbsp:·

set textwidth=110
set colorcolumn=+1

set splitbelow
set splitright

syntax on
