#!/bin/bash

# borrowed from https://github.com/toupeira/dotfiles/blob/503b929d30980d549ebef8d6da522d36b13d6e1e/tmux/scripts/search

key="$1"
command=$(tmux display -p '#{pane_current_command}')

shells=(bash zsh)

if ! [[ " ${shells[*]} " =~ " ${command} " ]]; then
  tmux send-keys "$key"
  exit 0
fi

tmux copy-mode

function search {
  tmux send-keys -X search-backward "$1"
}

case "$1" in
  # freeform search
  "") tmux send-keys ? ;;

  paths)
    path="[^][ '\"]"
    search "(/$path+|$path*/|$path*\.$path+)$path*"
    ;;

  prompts)
    search "^(.* )?\$.*"
    ;;

  # interesting things (URLs, emails, hashes, IPs)
  interesting)
    urls='(https?://|git@|git://|ssh://|ftp://|file:///)[[:alnum:]?=%/_.:,;~@!#$&()*+-]*'
    emails='[-_\.[:alnum:]]+@[-_\.[:alnum:]]+'
    hashes='\b(([0-9a-f]{7,40}|[[:alnum:]]{52}|[0-9a-f]{64})(\.{2,3})?)+\b'
    ips='[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}'

    search "($urls|$emails|$hashes|$ips)"
    ;;
esac

exit 0
