# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

#
# Exports
#
if [ -e ~/.exports ]; then
    . ~/.exports
fi

#
# SDKMAN!
#
if [ -e ~/.dotfiles/zsh/sdkman.sh ]; then
    #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
    . ~/.dotfiles/zsh/sdkman.sh
fi
