# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

####  zplug setup
[ -f ~/.zplug/init.zsh ] && source ~/.zplug/init.zsh

zplug 'zplug/zplug',						hook-build:'zplug --self-manage'

# perform tasks asynchronously
zplug "mafredri/zsh-async",					defer:0

# syntax highlight in the terminal
zplug "zsh-users/zsh-syntax-highlighting",	defer:3

# package manager for go, java, etc.
zplug "kiurchv/asdf.plugin.zsh",			defer:2

# flexible clipboard use from CLI
zplug "zpm-zsh/clipboard"

# fish like auto suggestions
zplug "zsh-users/zsh-autosuggestions"

# interactive CLI git
zplug "wfxr/forgit",						defer:1

# autostart tmux
#zplug "zpm-zsh/tmux"

# auto closes delimiters
zplug 'hlissner/zsh-autopair',				defer:2

# zsh theme
zplug romkatv/powerlevel10k,				as:theme, depth:1
#zplug "themes/steeef",                                         from:oh-my-zsh


# useful git aliases
zplug "plugins/git",						from:oh-my-zsh

# vi mode plug-in
zplug "plugins/vi-mode",					from:oh-my-zsh

# some oh-my-zsh useful plug-ins
zplug "lib/completion",						from:oh-my-zsh
zplug "lib/grep",							from:oh-my-zsh
zplug "lib/history",						from:oh-my-zsh
zplug "lib/directories",					from:oh-my-zsh

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load
####  end zplug setup

#
# Custom configurations
#

# brew autocomplete
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi


setopt rmstarsilent

# mac keybindings
if [[ "$OSTYPE" == "darwin"* ]]; then
	bindkey "^[^[[D" backward-word
	bindkey "^[^[[C" forward-word

	bindkey "^[a" beginning-of-line
	bindkey "^[e" end-of-line

	bindkey "ç" fzf-cd-widget
fi

# Exports
[[ -f ~/.exports ]] && source ~/.exports

# Aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# Local configurations
[[ -f ~/.zshrc_local ]] && source ~/.zshrc_local

# FZF
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
