# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="steeef"

# Uncomment the following line to use case-sensitive completion.
#CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS=true

plugins=(git)
plugins+=(colorize) 
plugins+=(github) 
plugins+=(docker) 
plugins+=(systemd) 
plugins+=(vi-mode)

source $ZSH/oh-my-zsh.sh

# User configuration

#
# Exports
#
if [ -f ~/.exports ]; then
    source ~/.exports
fi

#
# Aliases
#
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi

#
# Local configs
#
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi

# asdf
[ -e $HOME/.dotfiles/zsh/asdf.sh ] && source $HOME/.dotfiles/zsh/asdf.sh
