[package]
disabled=false

[python]
disabled=false

[git_branch]
disabled=false

[git_commit]
disabled=false

[git_state]
disabled=false

[git_status]
disabled=false
ignore_submodules=true
untracked = ""

[git_metrics]
disabled=false

[docker_context]
disabled=false

[java]
disabled=true

[kotlin]
disabled=true

[cmd_duration]
disabled=false
